#!/usr/bin/env zsh
bspc rule -r "*"

redshift -l 52:0 &
setxkbmap -layout us -variant dvp -option caps:super &
nitrogen --set-auto $HOME/images/mountains.jpg &
xrdb -load $XDG_CONFIG_HOME/X11/xresources &
sxhkd &
xcalib $HOME/.local/share/LP156WF6_SPK1.icm &
unclutter --timeout 1 --ignore-scrolling &
xset r rate 300 75 &
polybar -c $XDG_CONFIG_HOME/polybar/config.ini status_top &
xcape -e "Super_L=Escape" &

bspc monitor -d 1 2 3 4
bspc desktop -f 1

bspc config border_width 0
bspc config window_gap 4
bspc config top_padding 22
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled

echo Loaded!
