#!/usr/bin/env zsh
function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}
bspc rule -r "*"
pkill -9 pulseaudio
start-pulseaudio-x11 &
run redshift -l 52:0
setxkbmap -layout us -variant dvp -option ctrl:nocaps &
nitrogen --set-tiled --random $HOME/images/wallpapers/ &
xcalib $HOME/.local/share/LP156WF6_SPK1.icm &
run unclutter --timeout 1 --ignore-scrolling
xset r rate 300 75 &
run xcape -e "Control_L=Escape"

for monitor in $(bspc query -M --names); do
	bspc monitor "$monitor" -d I II III IV V VI VII VIII IX
done

bspc desktop -f I

restart_polybar
run sxhkd

bspc config border_width 0
bspc config window_gap 4
bspc config top_padding 22
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled

echo Loaded!
