#!/usr/bin/env zsh
function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}
bspc rule -r "*"
start-pulseaudio-x11 &
run redshift -l 52:0
setxkbmap -layout us -variant dvp -option ctrl:nocaps &
nitrogen --set-zoom-fill --random $HOME/images/wallpapers/ &
xrdb -load $XDG_CONFIG_HOME/X11/xresources &
xcalib $HOME/.local/share/LP156WF6_SPK1.icm &
run unclutter --timeout 1 --ignore-scrolling
xset r rate 300 75 &
run polybar -c $XDG_CONFIG_HOME/polybar/config.ini status_top
run xcape -e "Control_L=Escape"

bspc monitor -n "main"
bspc monitor -d I II III IV V VI VII VIII IX
bspc desktop -f I

run sxhkd

bspc config border_width 0
bspc config window_gap 4
bspc config top_padding 22
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled

echo Loaded!
